In [1]:
import sys
import sklearn

import tensorflow as tf
from tensorflow import keras

import numpy as np
import os

np.random.seed(42)
tf.random.set_seed(42)


# Char-RNN

## Splitting a sequence into batches of shuffled windows

In [2]:
np.random.seed(42)
tf.random.set_seed(42)

n_steps=5
dataset =tf.data.Dataset.from_tensor_slices(tf.range(15))
dataset = dataset.window(n_steps, shift=2, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(n_steps))
dataset = dataset.shuffle(10).map(lambda window: (window[:-1], window[1:]))
dataset = dataset.batch(3).prefetch(1)
for index, (X_batch, Y_batch) in enumerate(dataset):
    print("_" * 20, "Batch", index, "\nX_batch")
    print(X_batch.numpy())
    print("=" *5, "\nY_batch")
    print(Y_batch.numpy())

____________________ Batch 0 
X_batch
[[6 7 8 9]
 [2 3 4 5]
 [4 5 6 7]]
===== 
Y_batch
[[ 7  8  9 10]
 [ 3  4  5  6]
 [ 5  6  7  8]]
____________________ Batch 1 
X_batch
[[ 0  1  2  3]
 [ 8  9 10 11]
 [10 11 12 13]]
===== 
Y_batch
[[ 1  2  3  4]
 [ 9 10 11 12]
 [11 12 13 14]]


## Loading the Data and Preparing the Dataset

In [3]:
shakespeare_url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
filepath = keras.utils.get_file("shakespeare.txt", shakespeare_url)
with open(filepath) as f:
    shakespeare_text =f.read()

In [4]:
print(shakespeare_text[:148])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?



In [5]:
"".join(sorted(set(shakespeare_text.lower())))

"\n !$&',-.3:;?abcdefghijklmnopqrstuvwxyz"

In [6]:
tokenizer= keras.preprocessing.text.Tokenizer(char_level =True)
tokenizer.fit_on_texts(shakespeare_text)

In [7]:
tokenizer.texts_to_sequences(["First"])

[[20, 6, 9, 8, 3]]

In [8]:
tokenizer.sequences_to_texts([[20,6,9,8,3]])

['f i r s t']

In [9]:
max_id = len(tokenizer.word_index)
dataset_size = tokenizer.document_count

In [10]:
[encoded] = np.array(tokenizer.texts_to_sequences([shakespeare_text])) -1
train_size = dataset_size *90 //100
dataset= tf.data.Dataset.from_tensor_slices(encoded[:train_size])

In [11]:
n_steps = 100
window_length = n_steps +1
dataset = dataset.window(window_length, shift=1, drop_remainder =True)

In [12]:
dataset = dataset.flat_map(lambda window: window.batch(window_length))

In [13]:
np.random.seed(42)
tf.random.set_seed(42)

In [14]:
batch_size =32
dataset = dataset.shuffle(10000).batch(batch_size)
dataset = dataset.map(lambda windows: (windows[:, :-1], windows[:, 1:]))

In [15]:
dataset = dataset.map(lambda X_batch, Y_batch: (tf.one_hot(X_batch, depth=max_id), Y_batch))

In [16]:
dataset = dataset.prefetch(1)

In [17]:
for X_batch, Y_batch in dataset.take(1):
    print(X_batch.shape, Y_batch.shape)

(32, 100, 39) (32, 100)


## Creating and Training the Model

In [19]:
tf.test.gpu_device_name()

'/device:GPU:0'

In [18]:
model = keras.models.Sequential([keras.layers.GRU(128, return_sequences=True, input_shape = [None, max_id], 
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2),
                                 keras.layers.GRU(128, return_sequences=True,
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2),
                                 keras.layers.TimeDistributed(keras.layers.Dense(max_id, activation="softmax"))
                                ])
model.compile(loss="sparse_categorical_crossentropy", optimizer ="adam")
history= model.fit(dataset, epochs=10)

Epoch 1/10


2023-08-02 03:56:38.617818: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_NOT_INITIALIZED
2023-08-02 03:56:38.618020: E tensorflow/stream_executor/cuda/cuda_dnn.cc:398] Possibly insufficient driver version: 510.108.3
2023-08-02 03:56:38.618037: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : UNKNOWN: Fail to find the dnn implementation.


UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential/gru/PartitionedCall]] [Op:__inference_train_function_5730]

## handson-ml3のコードテスト

In [33]:
text_vec_layer=tf.keras.layers.TextVectorization(split='character', 
                                                 standardize='lower')
text_vec_layer.adapt([shakespeare_text])
encoded =text_vec_layer([shakespeare_text])[0]

In [34]:
encoded-=2
n_tokens= text_vec_layer.vocabulary_size()-2
dataset_size=len(encoded)

In [35]:
def to_dataset(sequence, length, shuffle=False, seed=None, batch_size=32):
    ds = tf.data.Dataset.from_tensor_slices(sequence)
    ds = ds.window(length + 1, shift=1, drop_remainder=True)
    ds = ds.flat_map(lambda window_ds: window_ds.batch(length + 1))
    if shuffle:
        ds = ds.shuffle(100_000, seed=seed)
    ds = ds.batch(batch_size)
    return ds.map(lambda window: (window[:, :-1], window[:, 1:])).prefetch(1)

In [36]:
length = 100
tf.random.set_seed(42)
train_set = to_dataset(encoded[:1_000_000], length=length, shuffle=True,
                       seed=42)
valid_set = to_dataset(encoded[1_000_000:1_060_000], length=length)
test_set = to_dataset(encoded[1_060_000:], length=length)

In [37]:
tf.random.set_seed(42)  # extra code – ensures reproducibility on CPU
model = tf.keras.Sequential([
    tf.keras.layers.Embedding(input_dim=n_tokens, output_dim=16),
    tf.keras.layers.GRU(128, return_sequences=True),
    tf.keras.layers.Dense(n_tokens, activation="softmax")
])
model.compile(loss="sparse_categorical_crossentropy", optimizer="nadam",
              metrics=["accuracy"])
model_ckpt = tf.keras.callbacks.ModelCheckpoint(
    "my_shakespeare_model", monitor="val_accuracy", save_best_only=True)
history = model.fit(train_set, validation_data=valid_set, epochs=10,
                    callbacks=[model_ckpt])

Epoch 1/10


2023-08-02 04:37:15.300984: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-08-02 04:37:15.301004: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : UNKNOWN: Fail to find the dnn implementation.


UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential_2/gru_4/PartitionedCall]] [Op:__inference_train_function_14587]

## Using the Model to Generate Text

In [22]:
def preprocess(texts):
    X=np.array(tokenizer.texts_to_sequences(texts))-1
    return tf.one_hot(X, max_id)

In [23]:
X_new=preprocess(["How are yo"])
Y_pred = np.argmax(model(X_new), axis=-1)
tokenizer.sequences_to_texts(Y_pred+1)[0][-1]

2023-08-02 04:06:15.268586: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-08-02 04:06:15.268632: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : UNKNOWN: Fail to find the dnn implementation.


UnknownError: Exception encountered when calling layer "gru" (type GRU).

Fail to find the dnn implementation. [Op:CudnnRNN]

Call arguments received by layer "gru" (type GRU):
  • inputs=tf.Tensor(shape=(1, 10, 39), dtype=float32)
  • mask=None
  • training=False
  • initial_state=None

In [24]:
tf.random.set_seed(42)

tf.random.categorical([[np.log(0.5), np.log(0.4), np.log(0.1)]], num_samples=40).numpy()

array([[0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0, 0, 1, 1, 1, 0, 0,
        2, 0, 0, 1, 1, 1, 0, 0, 1, 2, 0, 0, 1, 1, 0, 0, 0, 0]])

In [25]:
def next_char(text, temperature=1):
    X_new=preprocess([text])
    y_proba=model(X_new)[0, -1:, :]
    rescaled_logits = tf.math.log(y_proba)/ temperature
    char_id = tf.random.categorical(rescaled_logits, num_samples=1)+1
    return tokenizer.sequences_to_texts(char_id.numpy())[0]

In [ ]:
tf.random.set_seed(42)
next_char("How are yo", temperature=1)

In [ ]:
def complete_text(text, n_chars=50, temperature=1):
    for _ in range(n_chars):
        text += next_char(text, temperature)
    return text

In [ ]:
tf.random.set_seed(42)

print(complete_text("t", temperature=0.2))

In [ ]:
print(complete_text("t", temperature=1))

In [ ]:
print(complete_text("t", temperature=2))

# Stateful RNN

In [26]:
tf.random.set_seed(42)

In [27]:
dataset= tf.data.Dataset.from_tensor_slices(encoded[:train_size])
dataset = dataset.window(window_length, shift=n_steps, drop_remainder=True)
dataset=dataset.flat_map(lambda window: window.batch(window_length))
dataset=dataset.batch(1)
dataset=dataset.map(lambda windows:(windows[:,:-1], windows[:, 1:]))
dataset =dataset.map(lambda X_batch, Y_batch: (tf.one_hot(X_batch, depth=max_id), Y_batch))
dataset =dataset.prefetch(1)

In [28]:
batch_size=32
encoded_parts=np.array_split(encoded[:train_size], batch_size)
datasets=[]
for encoded_part in encoded_parts:
    dataset =tf.data.Dataset.from_tensor_slices(encoded_part)
    dataset=dataset.window(window_length, shift=n_steps, drop_remainder=True)
    dataset = dataset.flat_map(lambda window: window.batch(window_length))
    datasets.append(dataset)
dataset = tf.data.Dataset.zip(tuple(datasets)).map(lambda *windows: tf.stack(windows))
dataset= dataset.map(lambda windows: (windows[:,:-1], windows[:,1:]))
dataset = dataset.map(lambda X_batch, Y_batch:(tf.one_hot(X_batch, depth=max_id), Y_batch))
dataset = dataset.prefetch(1)

In [29]:
model = keras.models.Sequential([keras.layers.GRU(128, return_sequences=True, stateful=True, 
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2, 
                                                  batch_input_shape=[batch_size, None, max_id]),
                                 keras.layers.GRU(128, return_sequences=True,stateful =True,
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2),
                                 keras.layers.TimeDistributed(keras.layers.Dense(max_id, activation="softmax"))
                                ])

In [30]:
class ResetStatesCallback(keras.callbacks.Callback):
    def on_epoch_begin(self, epoch, logs):
        self.model.reset_states()

In [31]:
model.compile(loss="sparse_categorical_crossentropy", optimizer ="adam")
history= model.fit(dataset, epochs=50, 
                  callbacks=[ResetStatesCallback()])

Epoch 1/50


2023-08-02 04:17:53.453958: E tensorflow/stream_executor/cuda/cuda_dnn.cc:389] Could not create cudnn handle: CUDNN_STATUS_INTERNAL_ERROR
2023-08-02 04:17:53.453985: W tensorflow/core/framework/op_kernel.cc:1745] OP_REQUIRES failed at cudnn_rnn_ops.cc:1553 : UNKNOWN: Fail to find the dnn implementation.


UnknownError: Graph execution error:

Fail to find the dnn implementation.
	 [[{{node CudnnRNN}}]]
	 [[sequential_1/gru_2/PartitionedCall]] [Op:__inference_train_function_10826]

In [ ]:
stateless_model = keras.models.Sequential([
    keras.layers.GRU(128, return_sequences=True, input_shape = [None, max_id] ),
    keras.layers.GRU(128, return_sequences=True),
    keras.layers.TimeDistributed(keras.layers.Dense(max_id, activation="softmax"))
    ])


In [ ]:
stateless_model.build(tf.TensorShape([None, None, max_id]))

In [ ]:
stateless_model.set_weights(model.get_weights())
model = stateless_model

In [ ]:
tf.random.set_seed(42)
print(complete_text("t"))

# Sentiment Analysis

In [ ]:
tf.random.set_seed(42)

In [ ]:
(X_train, y_train), (X_test, y_test)= keras.datasets.imdb.load_data()

In [ ]:
X_train[0][:10]

In [ ]:
word_index=keras.datasets.imdb.get_word_index()
id_to_word={id_+3: word for word, id_ in word_index.items()}
for id_, token in enumerate(("<pad>", "<sos>", "<unk>")):
    id_to_word[id_] = token
" ".join([id_to_word[id_] for id_ in X_train[0][:10]])

In [ ]:
import tensorflow_datasets as tfds

datasets, info = tfds.load("imdb_reviews", as_supervised=True, with_info=True)

In [ ]:
datasets.keys()

In [ ]:
train_size= info.splits["train"].num_examples
test_size =info.splits["test"].num_examples

In [ ]:
train_size, test_size

In [ ]:
for X_batch, y_batch in datasets["train"].batch(2).take(1):
    for review, label in zip(X_batch.numpy(), y_batch.numpy()):
        print("Review:", review.decode("utf-8")[:200], "...")
        print("Label:", label, "=Positive" if label else "=Negative")
        print()

In [ ]:
def preprocess(X_batch, y_batch):
    X_batch = tf.strings.substr(X_batch, 0, 300)
    X_batch = tf.strings.regex_replace(X_batch, rb"<br\s*/?>", b" ")
    X_batch = tf.strings.regex_replace(X_batch, b"[^a-zA-Z']", b" ")
    X_batch = tf.strings.split(X_batch)
    return X_batch.to_tensor(default_value=b"<pad>"), y_batch
    

In [ ]:
preprocess(X_batch, y_batch)

In [ ]:
from collections import Counter

vocabulary = Counter()
for X_batch, y_batch in datasets["train"].batch(32).map(preprocess):
    for review in X_batch:
        vocabulary.update(list(review.numpy()))

In [ ]:
vocabulary.most_common()[:3]

In [ ]:
len(vocabulary)

In [ ]:
vocab_size= 10000
truncated_vocabulary=[word for word, count in vocabulary.most_common()[:vocab_size]]

In [ ]:
word_to_id= {word: index for index, word in enumerate(truncated_vocabulary)}
for word in b"This movie was faaaaaantastic".split():
    print(word_to_id.get(word) or vocab_size)

In [ ]:
words = tf.constant(truncated_vocabulary)
word_ids=tf.range(len(truncated_vocabulary),dtype = tf.int64)
vocab_init= tf.lookup.KeyValueTensorInitializer(words, word_ids)
num_oov_buckets =1000
table= tf.lookup.StaticVocabularyTable(vocab_init, num_oov_buckets)

In [ ]:
table.lookup(tf.constant([b"This movie was faaaaaantastic".split()]))

In [ ]:
def encode_words(X_batch, y_batch):
    return table.lookup(X_batch), y_batch

train_set = datasets["train"].batch(32).map(preprocess)
train_set = train_set.map(encode_words).prefetch(1)

In [ ]:
for X_batch, y_batch in train_ste.take(1):
    print(X_batch)
    print(y_batch)

In [ ]:
embed_size = 128
model = keras.models.Sequential([keras.layers.Embedding(vocab_size + num_oov_buckets, embed_size, 
                                                        mask_zero = True,
                                                        input_shape =[None]),
                                keras.layers.GRU(128, return_sequences= True), 
                                keras.layers.GRU(128), 
                                keras.layers.Dense(1, activation = "sigmoid")])
model.compile(loss= "binary_crossentropy", optimizer = "adam", metrics= ["accuracy"])
history= model.fit(train_set, epochs= 5)

In [ ]:
K =keras.backend
embed_size = 128
inputs = keras.layers.Input(shape= [None])
mask =keras.layers.Lambda(lambda inputs: K.not_equal(inputs, 0))(inputs)
z = keras.layers.Embedding(vocab_size + num_oov_buckets, embed_size)(inputs)
z= keras.layers.GRU(128, return_sequences= True)(z, mask = mask)
z = keras.layers.GRU(128)(z, mask =mask)
outputs = keras.layers.Dense(1, activation = "sigmoid")(z)
model = keras.model.Model(inputs=[inputs], outputs= [outputs])
model.compile(loss= "binary_crossentropy", optimizer = "adam", metrics= ["accuracy"])
history= model.fit(train_set, epochs= 5)

## Reusing Pretrained Embeddings

In [ ]:
tf.random.set_seed(42)

In [ ]:
TFHUB_CACHE_DIR = os.path.join(os.curdir, "my_tfhub_cache")
os.environ["TFHUB_CACHE_DIR"]=TFHUB_CACHE_DIR

In [ ]:
import tensorflow_hub as hub

model = keras.Seuential([hub.KerasLayer("https://tfhub.dev/google/tf2-preview/nnlm-en-dim50/1", 
                                       dtype =tf.string, input_shape=[], output_shape=[50]),
                        keras.layers.Dense(128, activation="relu"),
                        keras.layers.Dense(1, activation="sigmoid")])
model.compile(loss="binary_crossentropy", optimizer ="adam", metrics=["accuracy"])

In [ ]:
for dirpath, dirnames, filenames in os.walk(TFHUB_CACHE_DIR):
    for filename in filenames:
        print(os.path.join(dirpath, filename))

In [ ]:
import tensorflow_datasets as tfds

datasets, info =tfds.load("imdb_reviews", as_supervised=True, with_info= True)
train_size = info.splits["train"].num_examples
batch_size= 32
train_set= datasets["train"].batch(batch_size).prefetch(1)
history=model.fit(train_set, epochs=5)

## Automatic Translation

In [ ]:
tf.random.set_seed(42)

In [ ]:
vocab_size= 100
embed_size=10

In [ ]:
import tensorflow_addons as tfa

encoder_inputs = keras.layers.Input(shape=[None], dtype=np.int32)
decoder_inputs = keras.layers.Input(shape=[None], dtype=np.int32)
sequence_lengths = keras.layers.Input(shape=[], dtype=np.int32)

embeddings= keras.layers.Embedding(vocab_size, embed_size)
encoder_embeddings= embeddings(encoder_inputs)
decoder_embeddings= embeddings(decoder_inputs)

encoder = keras.layers.LSTM(512, return_state= True)
encoder_outputs, state_h, state_c = encoder(encoder_embeddings)
encoder_state= [state_h, state_c]

sampler= tfa.seq2seq.sampler.TrainingSampler()

decoder_cell= keras.layers.LSTMCell(512)
output_layer= keras.layers.Dense(vocab_size)
decoder= tfa.seq2seq.basic_decoder.BasicDecoder(decoder_cell, sampler, output_layer= output_layer)
final_outputs, final_state, final_sequence_lengths= decoder(
    decoder_embeddings, initial_state= encoder_state, 
    sequence_length= sequence_lengths)
Y_proba = tf.nn.softmax(final_outputs.rnn_output)

model= kers.models.Model(inputs=[encoder_inputs, decoder_inputs, seuence_length], outputs= [Y_proba])

In [ ]:
model.compile(loss= "sparse_categorical_crossentropy", optimizer= "adam")

In [ ]:
X=np.random.randint(100, size= 10*1000).reshape(1000, 10)
Y=np.random.randint(100, size= 15*1000).reshape(1000, 15)
X_decoder = np.c_[np.zeros((1000,1)), Y[:,:-1]]
seq_lengths = np.full([1000],15)

history= model.fit([X, X_decoder, seq_lengths], Y, epochs=2)

### Bidirectional Recurrent Layers

In [ ]:
model = keras.models.Sequential([
    keras.layers.GRU(10, return_sequences=True, input_shape = [None, 10]),
    keras.layers.Bidirectional(keras.layers.GRU(10, return_sequences= True))])

model.summary()

### Positional Encoding

In [ ]:
class PositionalEncoding(keras.layers.Layer):
    def __init__(self, max_steps, max_dims, dtype=tf.float32, **kwargs):
        super().__init__(dtype=dtype, **kwargs)
        if max_dims %2 == 1: max_dims +=1
        p, i=  np.meshgrid(np.arange(max_steps), np.arange(max_dims //2))
        pos_emb = np.empty((1, max_steps, max_dims))
        pos_emb[0, :,::2] = np.sin(p / 10000 ** (2 *i / max_dims)).T
        pos_emb[0, :,1::2] = np.cos(p / 10000 ** (2 *i / max_dims)).T
        self.positional_embedding = tf.constant(pos.emb.astype(self.dtype))
    def call(self, inputs):
        shape= tf.shape(inputs)
        return inputs+ self.positional_embedding[:, :shape[-2], :shape[-1]]

In [ ]:
max_steps=201
max_dims =512
pos_emb= PositionalEncoding(max_steps, max_dims)
PE=pos_emb(np.zeros((1, max_steps, max_dims), np.float32))[0].numpy()

In [ ]:
i1, i2, crop_i = 100, 101, 150
p1, p2, p3 = 22, 60, 35
fig, (ax1,ax2) = plt.subplots(nrows=2, ncols=1, sharex= True, figsize= (9,5))
ax1.plot([p1, p1], [-1,1], "k--", label = "$p = {}$".format(p1))
ax1.plot([p2, p2], [-1,1], "k--", label = "$p = {}$".format(p2), alpha =0.5)
ax1.plot(p3, PE[p3, i1],, "bx", label = "$p = {}$".format(p3))
ax1.plot(PE[:, i1], "b-", label = "$i = {}$".format(i1))
ax1.plot(PE[:, i2], "r-", label = "$i = {}$".format(i2))
ax1.plot([p1, p2],[PE[p1,i1], PE[p2, i1]], "bo")
ax1.plot([p1, p2],[PE[p1,i2], PE[p2, i2]], "bo")
ax1.legend(loc ="center right", fontsize =14, framealpha= 0.95)
ax1.set_ylabel= ("$P_{(p,i)}$", rotation=0, fontsize= 16)
ax1.grid(True, alpha=0.3)
ax1.hlines(0, 0, max_steps-1, color="k", linewidth = 1, alpha =0.3)
ax1.axis([0, max_steps-1, -1, 1])
ax2.imshow(PE.T[:crop_i], cmap="gray", interpolation= "bilinear", aspect="auto")
ax2.hlines(i1, 0, max_steps-1, color="r")
ax2.plot([p1, p1],[0, crop_i], "k--")
ax2.plot([p2, p2],[0, crop_i], "k--", alpha=0.5)
ax2.plot([p1, p2],[i2+cheat, i2+cheat], "ro")
ax2.plot([p1, p2],[i1, i1], "bo")
ax2.axis([0, max_steps-1, 0, crop_i])
ax2.set_xlabel('$p$', fontsize=16)
ax2.set_ylabel('$i$', rotation=0, fontsize=16)
plt.show()

In [ ]:
embed_size=512; max_steps=500; vocab_size=10000
encoder_inputs= keras.layers.Input(shape=[None], dtype = np.int32)
decoder_inputs= keras.layers.Input(shape=[None], dtype = np.int32)
embeddings = keras.layers.Embedding(vocab_size, embed_size)
encoder_embeddings= embeddings(encoder_inputs)
decoer_embeddings=embeddings(decoder_inputs)
positional_encoding = PositionalEncoding(max_steps, max_dims = embed_size)
encoder_in = positional_encoding(encoder_embeddings)
decoder_in = positional_encoding(decoder_embeddings)

In [ ]:
Z = encoder_in
for N in range(6):
    Z= keras.layers.Attention(use_scale=True)([Z, Z])
encoder_outputs= Z
Z= decoder_in
for N in range(6):
    Z= keras.layers.Attention(use_scale=True, causal=True)([Z,Z])
    Z= keras.layers.Attention(use_scale=True)([Z, encoder_outputs])
    
outputs=keras.layers.TimeDistributed(keras.layers.Dense(vocab_size, activation="softmax"))(Z)

In [ ]:
K = keras.backend

class MultiHeadAttention(keras.layers.Layer):
    def __init__(self, n_heads, causal = False, use_scale=False, **kwargs):
        self.n_heads= n_heads
        self.causal= causal
        self.use_scale =use_scale
        super().__init__(**kwargs)
    
    def build(self, batch_input_shape):
        self.dims= batch_input_shape[0][-1]
        self.q_dims, self.v_dims, self.k_dims = [self.dims//self.n_heads] *3
        self.q_linear = keras.layers.Conv1D(self.n_heads * self.q_dims, kernel_size= 1, use_bias= False)
        self.v_linear = keras.layers.Conv1D(self.n_heads * self.v_dims, kernel_size= 1, use_bias= False)
        self.k_linear = keras.layers.Conv1D(self.n_heads * self.k_dims, kernel_size= 1, use_bias= False)
        self.attention = keras.layers.Attention(causal= self.causal, use_scale= self.use_scale)
        self.out_linear= keras.layers.Conv1D(self.dims, kernel_size=1, use_bias= False)
        super().build(batch_input_shape)
    
    def _multi_head_linear(self, inputs, linear):
        shape= K.concatenate([K.shape(inputs)[:-1], [self.n_heads, -1]])
        projected= K.reshape(linear(inputs), shape)
        perm = K.permute_dimensions(projected, [0, 2, 1,3])
        return K.reshape(perm, [shape[0]*self.n_heads, shape[1], -1])
    
    def call(self, inputs):
        q = inputs[0]
        v= inputs[1]
        k = inputs[2] if len(inputs) > 2 else v
        shape = K.shape(q)
        q_proj = self._multi_head_linear(q, self.q_linear)
        v_proj = self._multi_head_linear(v, self.v_linear)
        k_proj = self._multi_head_linear(k, self.k_linear)
        multi_attended = self.attention([q_proj, v_proj, k_proj])
        shape_attended = K.shape(multi_attended)
        reshaped_attended= K.reshape(multi_attended, [shape[0], self.n_heads, shape_attended[1], shape_attended[2]])
        perm= K.permute_dimensions(reshaped_attended, [0, 2, 1,3])
        concat = K.reshape(perm, [shape[0], shape_attended[1],-1])
        return self.out_linear(concat)

In [ ]:
Q = np.random.rand(2, 50, 512)
V= np.random.rand(2, 80, 512)
multi_attn= MultiHeadAttention(8)
multi_attn([Q, V]).shape