In [4]:
import sys
import sklearn

import tensorflow as tf
from tensorflow import keras

import numpy as np
import os

np.random.seed(42)
tf.random.set_seed(42)


# Char-RNN

## Splitting a sequence into batches of shuffled windows

In [5]:
np.random.seed(42)
tf.random.set_seed(42)

n_steps=5
dataset =tf.data.Dataset.from_tensor_slices(tf.range(15))
dataset = dataset.window(n_steps, shift=2, drop_remainder=True)
dataset = dataset.flat_map(lambda window: window.batch(n_steps))
dataset = dataset.shuffle(10).map(lambda window: (window[:-1], window[1:]))
dataset = dataset.batch(3).prefetch(1)
for index, (X_batch, Y_batch) in enumerate(dataset):
    print("_" * 20, "Batch", index, "\nX_batch")
    print(X_batch.numpy())
    print("=" *5, "\nY_batch")
    print(Y_batch.numpy())

____________________ Batch 0 
X_batch
[[6 7 8 9]
 [2 3 4 5]
 [4 5 6 7]]
===== 
Y_batch
[[ 7  8  9 10]
 [ 3  4  5  6]
 [ 5  6  7  8]]
____________________ Batch 1 
X_batch
[[ 0  1  2  3]
 [ 8  9 10 11]
 [10 11 12 13]]
===== 
Y_batch
[[ 1  2  3  4]
 [ 9 10 11 12]
 [11 12 13 14]]


## Loading the Data and Preparing the Dataset

In [9]:
shakespeare_url = "https://raw.githubusercontent.com/karpathy/char-rnn/master/data/tinyshakespeare/input.txt"
filepath = keras.utils.get_file("shakespeare.txt", shakespeare_url)
with open(filepath) as f:
    shakespeare_text =f.read()

In [10]:
print(shakespeare_text[:148])

First Citizen:
Before we proceed any further, hear me speak.

All:
Speak, speak.

First Citizen:
You are all resolved rather to die than to famish?



In [11]:
"".join(sorted(set(shakespeare_text.lower())))

"\n !$&',-.3:;?abcdefghijklmnopqrstuvwxyz"

In [12]:
tokenizer= keras.preprocessing.text.Tokenizer(char_level =True)
tokenizer.fit_on_texts(shapespeare_text)

In [13]:
tokenizer.texts_to_sequences(["First"])

[[20, 6, 9, 8, 3]]

In [14]:
tokenizer.sequences_to_texts([[20,6,9,8,3]])

['f i r s t']

In [15]:
max_id = len(tokenizer.word_index)
dataset_size = tokenizer.document_count

In [16]:
[encoded] = np.array(tokenizer.texts_to_sequences([shapespeare_text])) -1
train_size = dataset_size *90 //100
dataset= tf.data.Dataset.from_tensor_slices(encoded[:train_size])

In [17]:
n_steps = 100
window_length = n_steps +1
dataset = dataset.window(window_length, shift=1, drop_remainder =True)

In [18]:
dataset = dataset.flat_map(lambda window: window.batch(window_length))

In [19]:
np.random.seed(42)
tf.random.set_seed(42)

In [20]:
batch_size =32
dataset = dataset.shuffle(10000).batch(batch_size)
dataset = dataset.map(lambda windows: (windows[:, :-1], windows[:, 1:]))

In [21]:
dataset = dataset.map(lambda X_batch, Y_batch: (tf.one_hot(X_batch, depth=max_id), Y_batch))

In [22]:
dataset = dataset.prefetch(1)

In [23]:
for X_batch, Y_batch in dataset.take(1):
    print(X_batch.shape, Y_batch.shape)

(32, 100, 39) (32, 100)


## Creating and Training the Model

In [ ]:
model = keras.models.Sequential([keras.layers.GRU(128, return_sequences=True, input_shape = [None, max_id], 
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2),
                                 keras.layers.GRU(128, return_sequences=True,
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2),
                                 keras.layers.TimeDistributed(keras.layers.Dense(max_id, activation="softmax"))
                                ])
model.compile(loss="sparse_categorical_crossentropy", optimizer ="adam")
history= model.fit(dataset, epochs=10)

## Using the Model to Generate Text

In [ ]:
def preprocess(texts):
    X=np.array(tokenizer.texts_to_sequences(texts))-1
    return tf.one_hot(X, max_id)

In [ ]:
X_new=preprocess(["How are yo"])
Y_pred = np.argmax(model(X_new), axis=-1)
tokenizer.sequences_to_texts(Y_pred+1)[0][-1]

In [ ]:
tf.random.set_seed(42)

tf.random.categorical([[np.log(0.5), np.log(0.4), np.log(0.1)]], num_samples=40).numpy()

In [ ]:
def next_char(text, temperature=1):
    X_new=preprocess([text])
    y_proba=model(X_new)[0, -1:, :]
    rescaled_logits = tf.math.log(y_proba)/ temperature
    char_id = tf.random.categorical(rescaled_logits, num_samples=1)+1
    return tokenizer.sequences_to_texts(char_id.numpy())[0]

In [ ]:
tf.random.set_seed(42)
next_char("How are yo", temperature=1)

In [ ]:
def complete_text(text, n_chars=50, temperature=1):
    for _ in range(n_chars):
        text += next_char(text, temperature)
    return text

In [ ]:
tf.random.set_seed(42)

print(complete_text("t", temperature=0.2))

In [ ]:
print(complete_text("t", temperature=1))

In [ ]:
print(complete_text("t", temperature=2))

# Stateful RNN

In [ ]:
tf.random.set_seed(42)

In [ ]:
dataset= tf.data.Dataset.from_tensor_slices(encoded[:train_size])
dataset = dataset.window(window_length, shift=n_steps, drop_remainder=True)
dataset=dataset.flat_map(lambda window: window.batch(window_length))
dataset=dataset.batch(1)
dataset=dataset.map(lambda windows:(windows[:,:-1], windows[:, 1:]))
dataset =dataset.map(lambda X_batch, Y_batch: (tf.one_hot(X_batch, depth=max_id), Y_batch))
dataset =dataset.prefetch(1)

In [ ]:
batch_size=32
encoded_parts=np.array_split(encoded[:train_size], batch_size)
datasets=[]
for encoded_part in encoded_parts:
    dataset =tf.data.Dataset.from_tensor_slices(encoded_part)
    dataset=dataset.window(window_length, shift=n_steps, drop_remainder=True)
    dataset = dataset.flat_map(lambda window: window.batch(window_length))
    datasets.append(dataset)
dataset = tf.data.Dataset.zip(tuple(datasets)).map(lambda *windows: tf.stack(windows))
dataset= dataset.map(lambda windows: (windows[:,:-1], windows[:,1:]))
dataset = dataset.map(lambda X_batch, Y_batch:(tf.one_hot(X_batch, depth=max_id), Y_batch))
dataset = dataset.prefetch(1)

In [ ]:
model = keras.models.Sequential([keras.layers.GRU(128, return_sequences=True, stateful=True, 
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2, 
                                                  batch_input_shape=[batch_size, None, max_id]),
                                 keras.layers.GRU(128, return_sequences=True,stateful =True,
                                                  # dropout=0.2, recurrent_dropout=0.2,
                                                  dropout =0.2),
                                 keras.layers.TimeDistributed(keras.layers.Dense(max_id, activation="softmax"))
                                ])

In [ ]:
class ResetStatesCallback(keras.callbacks.Callback):
    def on_epoch_begin(self, epoch, logs):
        self.model.reset_states()

In [ ]:
model.compile(loss="sparse_categorical_crossentropy", optimizer ="adam")
history= model.fit(dataset, epochs=50, 
                  callbacks=[ResetStatesCallback()])

In [ ]:
stateless_model = keras.models.Sequential([
    keras.layers.GRU(128, return_sequences=True, input_shape = [None, max_id] ),
    keras.layers.GRU(128, return_sequences=True),
    keras.layers.TimeDistributed(keras.layers.Dense(max_id, activation="softmax"))
    ])


In [ ]:
stateless_model.build(tf.TensorShape([None, None, max_id]))

In [ ]:
stateless_model.set_weights(model.get_weights())
model = stateless_model

In [ ]:
tf.random.set_seed(42)
print(complete_text("t"))

# Sentiment Analysis

In [ ]:
tf.random.set_seed(42)